name: Backend CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build and Test
        run: ./mvnw clean verify

      - name: Print Failsafe Reports
        if:  failure()
        run: |
          echo "==== failsafe txt reports ===="
          find target/failsafe-reports -name "*.txt" -print -exec cat {} \;
          echo "==== failsafe dumpstream reports ===="
          find target/failsafe-reports -name "*.dumpstream" -print -exec cat {} \;